### ISSUE TITLE
SciPy 2023 tracking issue

### ISSUE THREAD

**Issue by dcherian** [xarray-contrib/xarray-tutorial#170]
cc @scottyhq @lsetiawan @JessicaS11 @TomNicholas @andersy005 @negin513 

**Any one is welcome to contribute here, please reach out!**

### Logistics

As reminder, last year we created a [outline](https://tutorial.xarray.dev/workshops/scipy2022/README.html) for attendees (*max 90*) to follow. The outline links to a canonical copy of the material that gets updated every year, and serves as a syllabus for a future learner who did not necessarily attend the event.

I propose we do the same this year, and use the opportunity to develop some new canonical notebooks.

Here's our proposal outline converted to a todo list. I've added links to material that exists already. For bulllet items without a llink we need to develop new material (in most cases adapt the narrative documentation to tutorial format). Clearly we have a bunch of work to do :)

### Outline
- [ ]  Introduction/Logistics (@lsetiawan, @scottyhq)
    - [x] Nebari binder for SciPy tutorial? (about 100 simultaneous people)
    - [x] Add step-by-step Nebari instructions
    - [x] Request jupyterlab-myst
    - [ ] Update `scipy2023/index.ipynb`
	- [ ] Logistics (#171)
	- [ ] [Alignment and broadcasting](https://tutorial.xarray.dev/fundamentals/02.3_aligning_data_objects.html)
	- [ ] Address #188
	- [x] Address #68 
	- [x] Address #115,
	- [x] Add top-level banner / update left sidebar to guide attendees to right page (#189)
	- Optional
	  - [ ] Address #82, 
	  - [ ] Address #153
	  - [ ] Address #142?
	  - [ ] Address #85?
- [x] Indexing ([docs reference](https://docs.xarray.dev/en/stable/user-guide/indexing.html), @negin513 @andersy005 )
  - [Existing material](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html) 
  - [x] [Basic Indexing](https://tutorial.xarray.dev/fundamentals/02.1_working_with_labeled_data.html)
  - [x] Advanced and [Vectorized](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html#vectorized-indexing) Indexing
  - [x] Boolean Indexing and `isin`, and [masking](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html#indexing-with-where)
  - [x] Fancy Datetime Indexing
  - [x] Address #94 
- [x] [Computational Patterns](https://tutorial.xarray.dev/intermediate/01-high-level-computation-patterns.html) (@JessicaS11 @dcherian )
  - [x]  Address https://github.com/xarray-contrib/xarray-tutorial/issues/166
- [ ] Wrapping other arrays ([docs reference](https://docs.xarray.dev/en/stable/user-guide/duckarrays.html), @TomNicholas , @andersy005 )
  - [ ] Concepts
  - [x] [Introduction to Xarray wrapping Dask](https://tutorial.xarray.dev/intermediate/xarray_and_dask.html) (#196)
  - [ ] Demo of other arrays: [pint](https://tutorial.xarray.dev/intermediate/xarray_ecosystem.html#pint-via-duck-array-wrapping), sparse, cupy?
- [x] Wrapping custom computations: apply_ufunc ([docs reference](https://docs.xarray.dev/en/stable/user-guide/computation.html#wrapping-custom-computation)) (@dcherian, #180)
  - [x] [Concepts](https://tutorial.xarray.dev/advanced/apply_ufunc/simple_numpy_apply_ufunc.html) : core dimensions, 
  - [x] [Vectorizing](https://tutorial.xarray.dev/advanced/apply_ufunc/vectorize_1d.html)
  - [x] [Dask](https://tutorial.xarray.dev/advanced/apply_ufunc/simple_dask_apply_ufunc.html)
  - [ ] Address https://github.com/xarray-contrib/xarray-tutorial/issues/158
- [ ] Demo?
- [ ] Evaluation Survey?

### Notes

At a high level, we have to work on the indexing material, and the "duck array" material. The xarray docs on [indexing](https://docs.xarray.dev/en/stable/user-guide/indexing.html) are fairly comprehensive so it's mostly presenting that in a friendly manner. The [duck array](https://docs.xarray.dev/en/stable/user-guide/duckarrays.html) material is fairly minor, so that would be a decent lift.

**Comment by dcherian** [comment]
### Meeting Notes

-  [Meeting 1, June 2, 2023](https://docs.google.com/document/d/1Ty907ps1mBtf8QCuv_SkD_A1oDnRoVBhuDtXtMHNXfc/edit#)

**Comment by dcherian** [comment]
Pasting the email about Nebari for the SciPy tutorial

-----

We are emailing SciPy presenters to share an offer from Quansight to provide a hosted platform (JupyterHub, via [Nebari](https://www.nebari.dev/)) to run your tutorial.

Your workflow, and all participants' workflow, will involve: - Registering on the platform [1] (with any email and password), - Selecting a suitable machine [2] (i.e., adequate compute and storage for your tutorial), - Cloning the tutorial (git) repository in the JupyterLab interface that opens by default, - Teach your tutorial :)

As the presenter, you will have one extra step before the tutorial: create a suitable environment for your tutorial. If you have an environment.yml or requirements.txt file, this is a quick step which will take ~5 mins at most, and the Quansight team will assist you with this.

The platform (Nebari) has Dask integrated, and the capability to share files and dashboards within the platform. You can consider using this as an alternative to Binder, which currently has [reduced capacity and funding](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f). The Quansight team will be at SciPy in-person and will set up a dedicated Slack channel for support during the tutorial sessions.

If you're interested, please fill out this Google Form: https://forms.gle/recAwR1DaSau2Gsu6 by 25th June, and the Quansight team will reach out to share more information and schedule a live demo session to onboard you to the platform. If you have any questions, please contact Dharhas Pothina ([dharhas@quansight.com](mailto:dharhas@quansight.com)) or Pavithra Eswaramoorthy ([pavithraes@quansight.com](mailto:pavithraes@quansight.com)).

[1] Quansight won't collect or store your email on registering, you can also register with a fake email. [2] They will offer two types of machines for everyone: Small (2 CPUs, 8 GB RAM), Medium (4 CPUs, 16 GB RAM). If you need larger instances or a GPU instance, let them know in the Google Form and they will include it.

**Comment by scottyhq** [comment]
> I think we should do this! 

Sounds good to me! Small instances should be fine. @lsetiawan would you be willing to fill out the form and be the point of contact for this?

**Comment by dcherian** [comment]
@andersy005 @negin513 @TomNicholas can we get a quick update here please?

I think at this point, we could just plan to use the existing material as-is to reduce stress. There's definitely plenty of content!

**Comment by lsetiawan** [comment]
The rep from quansight will try to deploy it from the repo. I'm currently on vacation. I'll ping her again tomorrow.

> Hi Don,

I hope you have a nice vacation!

The onboarding meeting diverged off-topic, so I'll share a fresh set of instructions in a day or two. I'll also test the xarray tutorial on Nebari and let you know (or maybe open issues/PRs against the repo) if we need anything from you. :)

**Comment by negin513** [comment]
Hello @dcherian , 

I created a PR for the indexing notebooks. #192 

Regarding the last task under Indexing in the list above : 

> - [ ] Indexing ([docs reference](https://docs.xarray.dev/en/stable/user-guide/indexing.html), @negin513 @andersy005 )
>   - [Existing material](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html) 
>   - [ ] [Basic Indexing](https://tutorial.xarray.dev/fundamentals/02.1_working_with_labeled_data.html)
>   - [ ] Advanced and [Vectorized](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html#vectorized-indexing) Indexing
>   - [ ] Boolean Indexing and `isin`, and [masking](https://tutorial.xarray.dev/workshops/online-tutorial-series/02_indexing.html#indexing-with-where)
>   - [ ] Fancy Datetime Indexing
>   - [ ] Address #94 

I can write about broadcasting, aligning, etc in these notebooks. But was not sure if it fit nicely under indexing section. Do you envision having these under advanced indexing? Does it fit the advanced indexing or the computation section better? 

Here is the notebook for reference: 
https://tutorial.xarray.dev/workshops/online-tutorial-series/03_computation.html

**Comment by dcherian** [comment]
> I can write about broadcasting, aligning, etc in these notebooks. 

Sorry for being unclear. We can skip that for now. We already have material on alignment and broadcasting [here](https://tutorial.xarray.dev/fundamentals/02.3_aligning_data_objects.html)
